# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  url = "#about"
  weight = 1

[[main]]
  name = "Academic Programs"
  weight = 2
  url = "/post/academic_programs"

[[main]]
  name = "BAI 2020"
  weight = 3
  url = "/workshop/2020/cfp"

[[main]]
    name = "BAI 2019"
    weight = 4
    #parent = "ws"
    url = "/workshop/2019/cfp"

[[main]]
  name = "BAI 2018"
  weight = 5
  #parent = "ws"
  url = "/workshop/2018/cfp"

[[main]]
  name = "BAI 2017"
  weight = 6
  #parent = "ws"
  url = "/workshop/2017/cfp"

[[main]]
  name = "Contact"
  url = "#contact"
  weight = 7
